name: deploy website to Heroku
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # git clone
            - uses: actions/checkout@v2
            # linter
            michaelw90/PHP-Lint@master
